### ISSUE TITLE
Add Spotify support to Music widget

### ISSUE THREAD

**Issue by martinlexow** [martinlexow/superlayer-support#1]

**Comment by martinlexow** [comment]
Implemented! The Music Widget supports the Spotify app starting with Superlayer Version 1.0.4. If Apple Music and Spotify are playing at the same time, the first will be preferred.

**Comment by alessandro-newzoo** [comment]
@martinlexow hey, where can I find 1.0.4 please? The app store only gives me 1.0.3.

Impressive app by the way, so damn well designed!

**Comment by martinlexow** [comment]
@alessandro-newzoo It’s in the process of being released and currently “Waiting for Review”. The update will be available in the next few days through the Mac App Store! 🙂
