### ISSUE TITLE
Reminders Widget should have a maximum of items to load

### ISSUE THREAD

**Issue by BenedictSt** [martinlexow/superlayer-support#10]
When a list contains many reminders, the Reminders tap might take some time to load.
The issue might only occur after right-clicking the "Reminders 1" Widget in the Widgets tab.
Changing the style of the widget or switching from/to the Reminders tab results in a spinning beach ball or the app crashing completely.

Tested with around 300 reminders on M1.
#7 might help with fewer widgets to load, though the issue should still exist with large lists.

**Comment by martinlexow** [comment]
Version 1.0.3 is now live: It hides solved tasks and avoids to load more than 100 items per one Reminders widget. I would have preferred to limit them by time periods but unfortunately not every Reminder has such dates in its meta data, which makes filtering difficult. Do you mind this solution as approbiate?

**Comment by BenedictSt** [comment]
Yes, tested it and the issue is resolved. 👍

(Also, I think it isn't a huge deal since a list with 100+ reminders is nothing to deal with in an widget. But in v1.0.2 it was annoying that the app would crash if a list had a lot of items.)

**Comment by martinlexow** [comment]
Thanks so much for your feedback, Benedict! I’m glad the solution worked out. Will mark this issue as solved now.
