### ISSUE TITLE
Unable to edit widgets on second screen, "Show Superlayer" turning OFF I soon as I click anywhere

### ISSUE THREAD

**Issue by vincent-bidaux** [martinlexow/superlayer-support#14]
I can add widgets to my second screen — a HD screen attached to my LG Ultrafine 5K, hooked on a mac Mini.

But I can edit/manipulate the widgets on the second screen. I click Edit scene, then as soon as I try to click on the second screen on a widget or anywhere else, the edit mode vanishes and the widgets also disappear. I have to reactivate the edit and stop the edit on the main screen for the widgets to stay visible.

I just recorded a video, including all the steps I can think of for you to maybe understand the issue.
Please tell me what other tests I can perform to help you tackled this bug.

Screencast: [https://share.cleanshot.com/AvOXlz](https://share.cleanshot.com/AvOXlz)

**Comment by heponac** [comment]
Exactly the same happens for me. No problem to edit widgets on my main screen, and on the other screen they disappear as soon as I click on them ...

**Comment by martinlexow** [comment]
**Fixed it!** Thanks everyone for reporting this unfortunate bug and apologies for the circumstances. It’s fixed in Version 1.0.5 which I expected to be available next week!
