### ISSUE TITLE
[Inspiration] Reference for a Notepad widget

### ISSUE THREAD

**Issue by vincent-bidaux** [martinlexow/superlayer-support#15]
I'm using ToT by The Icon Factory, it's a small notepad that stays in sync across my computers — and iDevices — using iCloud.
It's cute and simple, straightforward.

[https://tot.rocks/](https://tot.rocks/)

**Comment by martinlexow** [comment]
There are no plans to make the contents of widgets directly manipulable at the moment. You could use the Text widget to display a note, but you would have to use the editor to write it. iCloud Sync on the other side is something I’m already thinking of / tinkering with and it may be available in a future update.

**Comment by heponac** [comment]
> I'm using ToT by The Icon Factory, it's a small notepad that stays in sync across my computers — and iDevices — using iCloud. It's cute and simple, straightforward.
> 
> https://tot.rocks/

Agree, ToT is the perfect small tool to keep recurrent text a click away !
