### ISSUE TITLE
Select more calendars at once

### ISSUE THREAD

**Issue by Kontor23** [martinlexow/superlayer-support#19]
Please allow the option to select more calendar at one. At the moment you can only chose between a single one or all. An in my Opinion calendars are one of the most important information on the desk. Thank you

Best Regards
MaK

**Comment by martinlexow** [comment]
Implemented! Multiple calendars will be selectable in the Calendar widget starting with Version 1.0.5. Expect this update to be available within the next week! Thanks for your feedback, really appreciate it.
