### ISSUE TITLE
[Feature Request] Pull content from online sources (eg. RSS, JSON, Folders)

### ISSUE THREAD

**Issue by alessandro-newzoo** [martinlexow/superlayer-support#21]
Hello it's me again :D 

I was thinking it'd be really cool if we could set up widgets to pull their content from online resources such as JSON urls or RSS feeds.

### **Some examples:**
- **Text widget:** Pull text from JSON urls or RSS feeds, so you can have like your quote of the day
- **Image:** Pull images from JSON, RSS, Google Photos, or Folders, so you can have rotating images pulled from online sources like Unsplash, or make your own collection through folders on your system or Google Photos albums

Apologies if this sounds too crazy :D The app is great but it feels all a bit too static when it comes to text/images, and I feel like these improvements would make me a lot happier to spend this kind of money on it :)

Thank you!

**Comment by martinlexow** [comment]
I agree with you that widgets should be as dynamic as possible! I had this in mind when designing Superlayer in the first place and it is one of the reasons why I implemented URL Schemes and Key Bindings.

**Remote control Text widgets:** I’ve added a new URL Scheme that allows to change the actual text of an existing Text widget:
`superlayer://updateTextWidget?widgetId=yourIdentifier&text=yourTextValue`
The `widgetId` is a unique identifier for each widget and can be found in the General tab. The `text` attribute expects a percent encoded String (i.e. `Hello%20world`).
Being able to call this URL from everywhere gives you maximum freedom.
This will be available in Version 1.0.5 and upwards.

**Displaying RSS Feeds**: I think this would be a new kind of widget. Here’s a separate [feature request](https://github.com/martinlexow/superlayer-support/issues/22) to discuss this further.

**Image widget with dynamic sources**: I do plan to implement a gallery widget that changes images from a given directory automatically in a time interval users can specify.

**Comment by alessandro-newzoo** [comment]
awesome work, thanks Martin! Can't wait to give 1.0.5 a try as soon as it's out! :)
