### ISSUE TITLE
floating bar on 1.0.5 macOS13

### ISSUE THREAD

**Issue by vincent-bidaux** [martinlexow/superlayer-support#24]
Freshly updated macOS and Superlayer, floating bar appears on desktop, doesn't go away when closing superlayer window.

![CleanShot 2022-10-26 at 09 11 28@2x](https://user-images.githubusercontent.com/3494919/197959025-232469a9-0ba5-4eb6-8fb2-f2e04718d132.png)

**Comment by martinlexow** [comment]
Hi Vincent — thanks for reporting, really appreciate your support! I’ve already fixed that bug in 1.0.6. The new version got accepted yesterday evening. It should be available now on the Mac App Store.

**Comment by martinlexow** [comment]
Absolutely! Also, making widgets more useful sounds way more fun than fixing bugs 😄
